### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by l29** [gabireze/tiktok-all-favorite-videos-remover#1]
Hey, great project! I've been searching for an extension like this for a while now. Is there a chance to add an option to remove all TikTok likes in this extension or create a separate extension for that purpose?

**Comment by gabireze** [comment]
Thanks for the suggestion, I thought it best to create a new project and with that, a new extension, to be able to add this functionality. This here is the repository: https://github.com/gabireze/tiktok-all-liked-videos-remover

I submitted it for approval to Chrome Web Store, probably between Monday and Tuesday of next week I'll already have an official link, and I will update the Chrome Web Store link in the repository as soon as it becomes available.

For now, you can download the repository on your machine and include it in your browser's extensions through the developer area (I explain this in the description of the projects).

Thank you for the suggestion, any questions, comments, or suggestions can be sent to me.

**Comment by gabireze** [comment]
The extension has been approved in the Chrome Web Store, this is the [link](https://chrome.google.com/webstore/detail/tiktok-all-liked-videos-r/eafmacjdgennnmhagdkdckgjokmnllci/related)!
